title: "RECO: Recovery Companion"
description: Monitoring patients with heart failure on their recovery journey.
# baseurl: "" # the subpath of your site, e.g. "/blog"
# url: "" # the base hostname & protocol for your site, e.g. "http://example.com"
theme: jekyll-theme-cayman
css: "docs/custom.css"
