title: "RECO: Recovery Companion"
description: Monitoring patients with heart failure on their recovery journey.
baseurl: "" # the subpath of your site, e.g. "/blog"
url: "" # the base hostname & protocol for your site, e.g. "http://example.com"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
