# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|reco| "https://github.com/recoverycompanion/reco#{reco}" }

# gem "rails"

source 'https://rubygems.org'
gem 'nokogiri'
gem 'rack', '~> 2.2.4'
gem 'rspec'